"""initial schema

Revision ID: c1a9c9b07fc8
Revises:
Create Date: 2026-09-30 21:12:50.121888

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c1a9c9b07fc8"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "connector",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "bitbucket",
                "github",
                "gitlab",
                name="connector_kind",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("base_url", sa.Text(), nullable=False),
        sa.Column("scope", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("credentials_ref", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_connector")),
        sa.UniqueConstraint("name", name=op.f("uq_connector_name")),
    )
    op.create_table(
        "rule_pack",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "core",
                "org",
                name="rule_pack_source",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rule_pack")),
        sa.UniqueConstraint("name", "version", name=op.f("uq_rule_pack_name")),
    )
    op.create_table(
        "space",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("parent_id", sa.BigInteger(), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["space.id"], name=op.f("fk_space_parent_id_space"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_space")),
        sa.UniqueConstraint("parent_id", "name", name=op.f("uq_space_parent_id")),
    )
    op.create_table(
        "tool_call",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("session_id", sa.String(length=128), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("tool", sa.String(length=64), nullable=False),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("result_count", sa.Integer(), nullable=True),
        sa.Column(
            "at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tool_call")),
    )
    op.create_index(op.f("ix_tool_call_request_id"), "tool_call", ["request_id"], unique=False)
    op.create_index(op.f("ix_tool_call_session_id"), "tool_call", ["session_id"], unique=False)
    op.create_table(
        "glossary_term",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("space_id", sa.BigInteger(), nullable=False),
        sa.Column("term", sa.String(length=200), nullable=False),
        sa.Column("target_node_id", sa.Text(), nullable=True),
        sa.Column("definition", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["space_id"],
            ["space.id"],
            name=op.f("fk_glossary_term_space_id_space"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_glossary_term")),
        sa.UniqueConstraint("space_id", "term", name=op.f("uq_glossary_term_space_id")),
    )
    op.create_table(
        "repository",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("connector_id", sa.BigInteger(), nullable=False),
        sa.Column("space_id", sa.BigInteger(), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("clone_url", sa.Text(), nullable=False),
        sa.Column("default_branch", sa.String(length=200), nullable=False),
        sa.Column(
            "selection",
            sa.Enum(
                "included",
                "discovered",
                "excluded",
                name="repository_selection",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("last_ingested_sha", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(
            ["connector_id"],
            ["connector.id"],
            name=op.f("fk_repository_connector_id_connector"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["space_id"],
            ["space.id"],
            name=op.f("fk_repository_space_id_space"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_repository")),
        sa.UniqueConstraint("connector_id", "name", name=op.f("uq_repository_connector_id")),
    )
    op.create_table(
        "ingestion_job",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("repository_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "trigger",
            sa.Enum(
                "initial",
                "merge",
                "manual",
                name="job_trigger",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "mode",
            sa.Enum(
                "full",
                "incremental",
                "dry_run",
                name="job_mode",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("from_sha", sa.String(length=64), nullable=True),
        sa.Column("to_sha", sa.String(length=64), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "running",
                "succeeded",
                "failed",
                name="job_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "queued_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("stats", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repository.id"],
            name=op.f("fk_ingestion_job_repository_id_repository"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingestion_job")),
    )
    op.create_index(
        "ix_ingestion_job_queue", "ingestion_job", ["status", "queued_at"], unique=False
    )
    op.create_table(
        "repository_rule_pack",
        sa.Column("repository_id", sa.BigInteger(), nullable=False),
        sa.Column("rule_pack_id", sa.BigInteger(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "reason",
            sa.Enum(
                "auto",
                "manual",
                name="rule_pack_reason",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repository.id"],
            name=op.f("fk_repository_rule_pack_repository_id_repository"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["rule_pack_id"],
            ["rule_pack.id"],
            name=op.f("fk_repository_rule_pack_rule_pack_id_rule_pack"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "repository_id", "rule_pack_id", name=op.f("pk_repository_rule_pack")
        ),
    )
    op.create_table(
        "coverage_item",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("job_id", sa.BigInteger(), nullable=False),
        sa.Column("repository_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "call_site",
                "annotation",
                name="coverage_kind",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("target_symbol", sa.Text(), nullable=False),
        sa.Column("occurrences", sa.Integer(), nullable=False),
        sa.Column("samples", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "open",
                "ignored",
                "covered",
                name="coverage_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["ingestion_job.id"],
            name=op.f("fk_coverage_item_job_id_ingestion_job"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repository.id"],
            name=op.f("fk_coverage_item_repository_id_repository"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_coverage_item")),
    )
    op.create_index(
        op.f("ix_coverage_item_repository_id"), "coverage_item", ["repository_id"], unique=False
    )
    op.create_table(
        "fact_change",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("job_id", sa.BigInteger(), nullable=False),
        sa.Column("fact_id", sa.Text(), nullable=False),
        sa.Column("fact_type", sa.String(length=64), nullable=False),
        sa.Column(
            "change",
            sa.Enum(
                "added",
                "removed",
                "modified",
                name="change_kind",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("before", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("commit_sha", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["ingestion_job.id"],
            name=op.f("fk_fact_change_job_id_ingestion_job"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fact_change")),
    )
    op.create_index(op.f("ix_fact_change_fact_id"), "fact_change", ["fact_id"], unique=False)
    op.create_index(op.f("ix_fact_change_job_id"), "fact_change", ["job_id"], unique=False)
    op.create_table(
        "ingestion_stage",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("job_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "stage",
            sa.Enum(
                "clone",
                "deps",
                "parse",
                "resolve",
                "flows",
                "write",
                "cards",
                name="stage_name",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "running",
                "succeeded",
                "failed",
                "skipped",
                name="stage_status",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("llm_cost", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("jev_cost", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["ingestion_job.id"],
            name=op.f("fk_ingestion_stage_job_id_ingestion_job"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingestion_stage")),
    )
    op.create_index(op.f("ix_ingestion_stage_job_id"), "ingestion_stage", ["job_id"], unique=False)
    op.create_table(
        "job_commit",
        sa.Column("job_id", sa.BigInteger(), nullable=False),
        sa.Column("commit_sha", sa.String(length=64), nullable=False),
        sa.Column("pr_number", sa.Integer(), nullable=True),
        sa.Column("pr_url", sa.Text(), nullable=True),
        sa.Column("merged_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["ingestion_job.id"],
            name=op.f("fk_job_commit_job_id_ingestion_job"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("job_id", "commit_sha", name=op.f("pk_job_commit")),
    )
    op.create_table(
        "jev_decision",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("stage_id", sa.BigInteger(), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("decision", sa.String(length=64), nullable=False),
        sa.Column("input", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("output", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("confidence", sa.Double(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["stage_id"],
            ["ingestion_stage.id"],
            name=op.f("fk_jev_decision_stage_id_ingestion_stage"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jev_decision")),
    )
    op.create_index(
        op.f("ix_jev_decision_request_id"), "jev_decision", ["request_id"], unique=False
    )
    op.create_index(op.f("ix_jev_decision_stage_id"), "jev_decision", ["stage_id"], unique=False)
    op.create_table(
        "llm_call",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("job_id", sa.BigInteger(), nullable=True),
        sa.Column("stage_id", sa.BigInteger(), nullable=True),
        sa.Column("node_id", sa.Text(), nullable=True),
        sa.Column("purpose", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("cached_tokens", sa.Integer(), nullable=False),
        sa.Column("cost", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["ingestion_job.id"],
            name=op.f("fk_llm_call_job_id_ingestion_job"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["stage_id"],
            ["ingestion_stage.id"],
            name=op.f("fk_llm_call_stage_id_ingestion_stage"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_llm_call")),
    )
    op.create_index(op.f("ix_llm_call_job_id"), "llm_call", ["job_id"], unique=False)
    op.create_table(
        "llm_output",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("llm_call_id", sa.BigInteger(), nullable=False),
        sa.Column("node_id", sa.Text(), nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["llm_call_id"],
            ["llm_call.id"],
            name=op.f("fk_llm_output_llm_call_id_llm_call"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_llm_output")),
    )
    op.create_index(
        "ix_llm_output_lookup", "llm_output", ["node_id", "kind", "input_hash"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_llm_output_lookup", table_name="llm_output")
    op.drop_table("llm_output")
    op.drop_index(op.f("ix_llm_call_job_id"), table_name="llm_call")
    op.drop_table("llm_call")
    op.drop_index(op.f("ix_jev_decision_stage_id"), table_name="jev_decision")
    op.drop_index(op.f("ix_jev_decision_request_id"), table_name="jev_decision")
    op.drop_table("jev_decision")
    op.drop_table("job_commit")
    op.drop_index(op.f("ix_ingestion_stage_job_id"), table_name="ingestion_stage")
    op.drop_table("ingestion_stage")
    op.drop_index(op.f("ix_fact_change_job_id"), table_name="fact_change")
    op.drop_index(op.f("ix_fact_change_fact_id"), table_name="fact_change")
    op.drop_table("fact_change")
    op.drop_index(op.f("ix_coverage_item_repository_id"), table_name="coverage_item")
    op.drop_table("coverage_item")
    op.drop_table("repository_rule_pack")
    op.drop_index("ix_ingestion_job_queue", table_name="ingestion_job")
    op.drop_table("ingestion_job")
    op.drop_table("repository")
    op.drop_table("glossary_term")
    op.drop_index(op.f("ix_tool_call_session_id"), table_name="tool_call")
    op.drop_index(op.f("ix_tool_call_request_id"), table_name="tool_call")
    op.drop_table("tool_call")
    op.drop_table("space")
    op.drop_table("rule_pack")
    op.drop_table("connector")
    # ### end Alembic commands ###
